---
###################################################
# Persistence Volume Claim for index
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index
spec:
  accessModes:
    - ReadWriteOnce
  # The default storageClassName is used here.
  # You can overwrite the classname
  # storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---
###################################################
# Deployment office-demo
###################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imixs-office-workflow
  labels:
    app: imixs-office-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imixs-office-workflow
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imixs-office-workflow
    spec:
      # Pod-level security context
      securityContext:
        fsGroup: 1000 # GID des jboss users
        runAsUser: 1000 # UID des jboss users
        runAsNonRoot: true
      containers:
        - name: imixs-office-workflow
          image: imixs/imixs-office-workflow:latest
          imagePullPolicy: Always
          # Container-level security context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_CONNECTION
              value: jdbc:postgresql://db/office
            - name: POSTGRES_PASSWORD
              value: adminadmin
            - name: POSTGRES_USER
              value: postgres
            - name: TZ
              value: CET
            - name: LANG
              value: "en_US.UTF-8"
            - name: MAILGATEWAY
              value: "localhost"

          ports:
            - name: web
              containerPort: 8080
            - name: admin
              containerPort: 9990
          livenessProbe:
            httpGet:
              path: /health
              port: 9990
            initialDelaySeconds: 60
            periodSeconds: 5
          # Memory Request and Limits
          resources:
            requests:
              memory: 600Mi

          volumeMounts:
            - mountPath: /opt/jboss/lucene
              name: index
      restartPolicy: Always
      volumes:
        - name: index
          persistentVolumeClaim:
            claimName: index

---
###################################################
# Service imixs-office-workflow
###################################################
apiVersion: v1
kind: Service
metadata:
  name: imixs-office-workflow
  labels:
    app: imixs-office-workflow
spec:
  ports:
    - name: web
      port: 8080
    - name: admin
      port: 9990
  selector:
    app: imixs-office-workflow
